export const GET_ALL_CHAMPS = "GET_ALL_CHAMPS";
export const GET_CHAMP_DETAIL = "GET_CHAMP_DETAIL";
export const ADD_CHAMPS_FAVORITE = "ADD_FAVORITE";
export const REMOVE_CHAMPS_FROM_FAVORITE = "REMOVE_CHAMPS_FROM_FAVORITE";
export const SET_FILTER = "SET_FILTER";
export const CLEAR_FAVORITES = "CLEAR_FAVORITES";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
